const indiaPackages = [
    // States of India
    {
        title: 'Spiritual Heritage of Amaravati',
        location: 'Andhra Pradesh, India',
        continent: 'Asia',
        price: 180,
        description: 'Discover the ancient Buddhist sites, the mesmerizing beaches of Vizag, and the divine Tirupati temple in Andhra Pradesh.',
        image: 'https://images.unsplash.com/photo-1581010866019-907fd9944524?auto=format&fit=crop&q=80&w=1200',
        duration: '6 days',
        maxGroupSize: 15,
        difficulty: 'easy',
        featured: false
    },
    {
        title: 'Dawn-Lit Mountains Safari',
        location: 'Arunachal Pradesh, India',
        continent: 'Asia',
        price: 350,
        description: 'Explore the mystic Land of the Rising Sun. Visit Tawang Monastery, Ziro Valley, and the pristine mountain landscapes of the Himalayas.',
        image: 'https://images.unsplash.com/photo-1626082896492-766af4eb6501?auto=format&fit=crop&q=80&w=1200',
        duration: '8 days',
        maxGroupSize: 10,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Tea Gardens & Rhino Trails',
        location: 'Assam, India',
        continent: 'Asia',
        price: 280,
        description: 'Experience the wilderness of Kaziranga National Park and the lush tea estates of Dibrugarh in the heart of the Northeast.',
        image: 'https://images.unsplash.com/photo-1571501201812-f67822f9bc9a?auto=format&fit=crop&q=80&w=1200',
        duration: '5 days',
        maxGroupSize: 12,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Enlightenment at Bodh Gaya',
        location: 'Bihar, India',
        continent: 'Asia',
        price: 150,
        description: 'Trace the roots of Buddhism and Jainism. Visit the Mahabodhi Temple and the ancient ruins of Nalanda University.',
        image: 'https://images.unsplash.com/photo-1610448721566-473ce9dafb11?auto=format&fit=crop&q=80&w=1200',
        duration: '4 days',
        maxGroupSize: 20,
        difficulty: 'easy',
        featured: false
    },
    {
        title: 'Tribal Culture & Chitrakote Falls',
        location: 'Chhattisgarh, India',
        continent: 'Asia',
        price: 220,
        description: 'Witness the Niagara of India at Chitrakote and explore the rich tribal heritage and ancient temples of Bastar.',
        image: 'https://images.unsplash.com/photo-1625505826533-5c80aca7d157?auto=format&fit=crop&q=80&w=1200',
        duration: '6 days',
        maxGroupSize: 10,
        difficulty: 'medium',
        featured: false
    },
    {
        title: 'Sun, Sand & Seafood',
        location: 'Goa, India',
        continent: 'Asia',
        price: 120,
        description: 'The ultimate beach vacation. From North Goa parties to South Goa serenity, enjoy the coastal vibes and spice plantations.',
        image: 'https://images.unsplash.com/photo-1512757776214-26d36777b513?auto=format&fit=crop&q=80&w=1200',
        duration: '4 days',
        maxGroupSize: 25,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'White Desert Rann Utsav',
        location: 'Gujarat, India',
        continent: 'Asia',
        price: 320,
        description: 'Experience the majestic Great Rann of Kutch, the Gir lions, and the architectural marvels of Ahmedabad and Dwarka.',
        image: 'https://images.unsplash.com/photo-1590050752117-23a97b62b45f?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 15,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Heritage Trails of Pinjore',
        location: 'Haryana, India',
        continent: 'Asia',
        price: 140,
        description: 'Visit the historic Kurukshetra, the beautiful Pinjore Gardens, and explore the modern skyline of Gurugram.',
        image: 'https://images.unsplash.com/photo-1622322062681-3c2243e8ba32?auto=format&fit=crop&q=80&w=1200',
        duration: '3 days',
        maxGroupSize: 15,
        difficulty: 'easy',
        featured: false
    },
    {
        title: 'Snowy Peaks of Spiti',
        location: 'Himachal Pradesh, India',
        continent: 'Asia',
        price: 450,
        description: 'A paradise for trekkers and nature lovers. Explore Shimla, Manali, Kasol, and the high-altitude desert of Spiti Valley.',
        image: 'https://images.unsplash.com/photo-1573030263696-ed7a5611484e?auto=format&fit=crop&q=80&w=1200',
        duration: '9 days',
        maxGroupSize: 12,
        difficulty: 'hard',
        featured: true
    },
    {
        title: 'Temples & Waterfalls Tour',
        location: 'Jharkhand, India',
        continent: 'Asia',
        price: 190,
        description: 'Visit the Deoghar temple and the scenic Hundru and Jonha falls in the Land of Forests.',
        image: 'https://images.unsplash.com/photo-1589136142558-946f1aa9317d?auto=format&fit=crop&q=80&w=1200',
        duration: '5 days',
        maxGroupSize: 15,
        difficulty: 'easy',
        featured: false
    },
    {
        title: 'Majestic Hampi Ruins',
        location: 'Karnataka, India',
        continent: 'Asia',
        price: 380,
        description: 'From the tech hub Bangalore to the heritage ruins of Hampi and the coffee hills of Coorg and Chikmagalur.',
        image: 'https://images.unsplash.com/photo-1580238053495-b9720401fd45?auto=format&fit=crop&q=80&w=1200',
        duration: '8 days',
        maxGroupSize: 12,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'God\'s Own Country Backwaters',
        location: 'Kerala, India',
        continent: 'Asia',
        price: 340,
        description: 'Relax in a houseboat at Alleppey, enjoy the tea gardens of Munnar, and witness the Kathakali dance in Kochi.',
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 10,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Heart of India Wildlife Safari',
        location: 'Madhya Pradesh, India',
        continent: 'Asia',
        price: 420,
        description: 'Explore the temples of Khajuraho and go on a tiger safari in Kanha and Bandhavgarh National Parks.',
        image: 'https://images.unsplash.com/photo-1616422285623-13ff0167c95c?auto=format&fit=crop&q=80&w=1200',
        duration: '8 days',
        maxGroupSize: 8,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Ajanta Elora Caves Heritage',
        location: 'Maharashtra, India',
        continent: 'Asia',
        price: 390,
        description: 'Experience the fast-paced Mumbai, the serene hill stations of Lonavala, and the ancient masterpieces of Ajanta and Ellora.',
        image: 'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 15,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Jewel City Imphal Explorer',
        location: 'Manipur, India',
        continent: 'Asia',
        price: 260,
        description: 'Visit the Loktak Lake and the floating Keibul Lamjao National Park in the beautiful state of Manipur.',
        image: 'https://images.unsplash.com/photo-1589136142558-946f1aa9317d?auto=format&fit=crop&q=80&w=1200',
        duration: '5 days',
        maxGroupSize: 10,
        difficulty: 'easy',
        featured: false
    },
    {
        title: 'Clouds & Waterfalls in Shillong',
        location: 'Meghalaya, India',
        continent: 'Asia',
        price: 310,
        description: 'The Scotland of the East. Visit the Mawlynnong village, the living root bridges, and the wettest place on earth, Cherrapunji.',
        image: 'https://images.unsplash.com/photo-1505436329302-60273767f401?auto=format&fit=crop&q=80&w=1200',
        duration: '6 days',
        maxGroupSize: 10,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Blue Mountains of Mizoram',
        location: 'Mizoram, India',
        continent: 'Asia',
        price: 270,
        description: 'Explore the rolling hills of Aizawl and the stunning landscapes of Phawngpui and the Vantawng Falls.',
        image: 'https://images.unsplash.com/photo-1582236544458-18e3a241e57c?auto=format&fit=crop&q=80&w=1200',
        duration: '6 days',
        maxGroupSize: 12,
        difficulty: 'medium',
        featured: false
    },
    {
        title: 'Nagaland Hornbill Festival',
        location: 'Nagaland, India',
        continent: 'Asia',
        price: 360,
        description: 'Experience the unique Naga culture during the Hornbill festival and explore the beautiful Dzukou valley.',
        image: 'https://images.unsplash.com/photo-1589136142558-946f1aa9317d?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 10,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Konark Sun Temple Heritage',
        location: 'Odisha, India',
        continent: 'Asia',
        price: 240,
        description: 'Experience the architectural marvel of Konark, the spiritual vibes of Puri, and the Chilika Lake wildlife.',
        image: 'https://images.unsplash.com/photo-1599427303058-f06cb9e980ee?auto=format&fit=crop&q=80&w=1200',
        duration: '6 days',
        maxGroupSize: 15,
        difficulty: 'easy',
        featured: false
    },
    {
        title: 'Golden Temple & Wagah Border',
        location: 'Punjab, India',
        continent: 'Asia',
        price: 200,
        description: 'Immerse in the spirituality of the Golden Temple and witness the patriotic ceremony at the Wagah Border.',
        image: 'https://images.unsplash.com/photo-1588096344316-f57c5035272a?auto=format&fit=crop&q=80&w=1200',
        duration: '4 days',
        maxGroupSize: 20,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Royal Rajasthan Forts & Palaces',
        location: 'Rajasthan, India',
        continent: 'Asia',
        price: 480,
        description: 'The Land of Kings. Visit Jaipur, Udaipur, Jodhpur, and Jaisalmer for a truly royal experience in the desert.',
        image: 'https://images.unsplash.com/photo-1532375811400-d757fb4005e1?auto=format&fit=crop&q=80&w=1200',
        duration: '10 days',
        maxGroupSize: 12,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Sikkim Monastery & Lake Tour',
        location: 'Sikkim, India',
        continent: 'Asia',
        price: 330,
        description: 'The gateway to the Himalayas. Explore Gangtok, Tsomgo Lake, and the serene monasteries nestled in the mountains.',
        image: 'https://images.unsplash.com/photo-1594144408013-4028bc74892c?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 10,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Temple Run Chennai to Madurai',
        location: 'Tamil Nadu, India',
        continent: 'Asia',
        price: 290,
        description: 'Discover the architectural brilliance of the Meenakshi Temple and the cultural depth of Chennai and Pondicherry nearby.',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 15,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Charminar & Hyderabadi Cuisine',
        location: 'Telangana, India',
        continent: 'Asia',
        price: 210,
        description: 'Experience the history of the Nizams at Charminar and Golconda Fort, and enjoy the world-famous Biryani.',
        image: 'https://images.unsplash.com/photo-1626241088710-85f269a9101d?auto=format&fit=crop&q=80&w=1200',
        duration: '4 days',
        maxGroupSize: 15,
        difficulty: 'easy',
        featured: false
    },
    {
        title: 'Unexplored Tripura Heritage',
        location: 'Tripura, India',
        continent: 'Asia',
        price: 230,
        description: 'Visit the Neermahal palace and the stunning rock cuts of Unakoti in the quaint state of Tripura.',
        image: 'https://images.unsplash.com/photo-1589136142558-946f1aa9317d?auto=format&fit=crop&q=80&w=1200',
        duration: '5 days',
        maxGroupSize: 10,
        difficulty: 'easy',
        featured: false
    },
    {
        title: 'Varanasi Ghats & Taj Mahal',
        location: 'Uttar Pradesh, India',
        continent: 'Asia',
        price: 450,
        description: 'The spiritual heart of India. Experience the evening Aarti at Varanasi and the eternal symbol of love, Taj Mahal at Agra.',
        image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&q=80&w=1200',
        duration: '8 days',
        maxGroupSize: 15,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Yoga Capital Rishikesh Retreat',
        location: 'Uttarakhand, India',
        continent: 'Asia',
        price: 370,
        description: 'Find inner peace in the Yoga capital of the world, Rishikesh, and go on an adventure trek in the Valley of Flowers.',
        image: 'https://images.unsplash.com/photo-1545105511-930909673907?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 12,
        difficulty: 'hard',
        featured: true
    },
    {
        title: 'Calcutta Heritage & Sundarbans',
        location: 'West Bengal, India',
        continent: 'Asia',
        price: 280,
        description: 'Experience the colonial charm of Kolkata and the mystery of the Royal Bengal Tiger in the Sundarbans mangrove forests.',
        image: 'https://images.unsplash.com/photo-1558434023-9c56f7afbc0c?auto=format&fit=crop&q=80&w=1200',
        duration: '6 days',
        maxGroupSize: 12,
        difficulty: 'medium',
        featured: true
    },

    // Union Territories
    {
        title: 'Emerald Isles of Andaman',
        location: 'Andaman & Nicobar Islands, India',
        continent: 'Asia',
        price: 520,
        description: 'A tropical paradise. Visit Havelock Island, Cellular Jail, and experience world-class scuba diving.',
        image: 'https://images.unsplash.com/photo-1589197331516-4d839bb12448?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 10,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Modernity Meets History',
        location: 'Delhi, India',
        continent: 'Asia',
        price: 250,
        description: 'From the Red Fort to the Lotus Temple, experience the vibrant chaos and rich history of India\'s capital.',
        image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&q=80&w=1200',
        duration: '4 days',
        maxGroupSize: 20,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Paradise Regained in Kashmir',
        location: 'Jammu & Kashmir, India',
        continent: 'Asia',
        price: 410,
        description: 'Experience the Shikara ride on Dal Lake, the snows of Gulmarg, and the breathtaking beauty of Pahalgam.',
        image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&q=80&w=1200',
        duration: '8 days',
        maxGroupSize: 12,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Moon Landscapes of Ladakh',
        location: 'Ladakh, India',
        continent: 'Asia',
        price: 580,
        description: 'The ultimate adventure. Visit Pangong Lake, Nubra Valley, and the high mountain passes in the Land of High Passes.',
        image: 'https://images.unsplash.com/photo-1581791534721-e599df4417f7?auto=format&fit=crop&q=80&w=1200',
        duration: '10 days',
        maxGroupSize: 8,
        difficulty: 'hard',
        featured: true
    },

    // International Packages
    {
        title: 'Majestic Swiss Alps',
        location: 'Interlaken, Switzerland',
        continent: 'Europe',
        price: 950,
        description: 'Experience the snow-capped mountains, crystal clear lakes, and luxury watches in the heart of Europe.',
        image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&q=80&w=1200',
        duration: '7 days',
        maxGroupSize: 12,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'African Safari Adventure',
        location: 'Maasai Mara, Kenya',
        continent: 'Africa',
        price: 850,
        description: 'Witness the great migration and the Big Five in their natural habitat in the world-famous Maasai Mara.',
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1200',
        duration: '6 days',
        maxGroupSize: 10,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Amazon Rainforest Expedition',
        location: 'Manaus, Brazil',
        continent: 'America',
        price: 1100,
        description: 'Dive deep into the world\'s largest tropical rainforest. Explore unique biodiversity and indigenous cultures.',
        image: 'https://images.unsplash.com/photo-1516939117205-054179e3f140?auto=format&fit=crop&q=80&w=1200',
        duration: '9 days',
        maxGroupSize: 8,
        difficulty: 'hard',
        featured: false
    },
    {
        title: 'Grand Canyon Helicopter Tour',
        location: 'Arizona, USA',
        continent: 'America',
        price: 1200,
        description: 'Experience one of the seven natural wonders of the world from above and below. Truly breathtaking landscapes.',
        image: 'https://images.unsplash.com/photo-1502472992487-601746f39ee1?auto=format&fit=crop&q=80&w=1200',
        duration: '5 days',
        maxGroupSize: 15,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Santorini Sunset Romance',
        location: 'Oia, Greece',
        continent: 'Europe',
        price: 750,
        description: 'Enjoy the iconic white buildings, blue domes, and the most beautiful sunsets in the world in Santorini.',
        image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=1200',
        duration: '5 days',
        maxGroupSize: 20,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Ancient Egypt Mystery',
        location: 'Cairo, Egypt',
        continent: 'Africa',
        price: 680,
        description: 'Visit the Great Pyramids of Giza, the Sphinx, and sail down the Nile in this historic journey through time.',
        image: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&q=80&w=1200',
        duration: '8 days',
        maxGroupSize: 15,
        difficulty: 'medium',
        featured: true
    },
    {
        title: 'Maldives Overwater Bliss',
        location: 'Male, Maldives',
        continent: 'Asia',
        price: 1500,
        description: 'Stay in luxury overwater villas, swim with manta rays, and enjoy pristine turquoise waters in paradise.',
        image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=1200',
        duration: '5 days',
        maxGroupSize: 2,
        difficulty: 'easy',
        featured: true
    },
    {
        title: 'Northern Lights Quest',
        location: 'Reyjavik, Iceland',
        continent: 'Europe',
        price: 1300,
        description: 'Chase the Aurora Borealis, visit the Blue Lagoon, and experience the land of fire and ice.',
        image: 'https://images.unsplash.com/photo-1490667195955-d6021d0f976a?auto=format&fit=crop&q=80&w=1200',
        duration: '6 days',
        maxGroupSize: 12,
        difficulty: 'medium',
        featured: true
    }
];

module.exports = indiaPackages;
